### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by rafalolszewski94** [J-T-McC/vue3-chartjs#11]
Can we expect TypeScript support anytime soon?

My project (as many others I assume) rely on TS and that would be great addition to the package itself with better completion.

*I have no experience in typing packages

**Comment by J-T-McC** [comment]
I don't have a timeframe for this as of yet but its on my list of things. TypeScript is new to me, so I have some learning to do before I push anything out in this area.

**Comment by productdevbook** [comment]
some problem

**Comment by neoighodaro** [comment]
Same issue as well

**Comment by grubshka** [comment]
> Hey @J-T-McC any update on this ? your plugin look great but i can't use it without Ts definition :/

I don't understand why you can't use it ? It works like a charm with typescript, you just don't have autocompletion and IDE hints on types.
I added `declare module "@j-t-mcc/vue3-chartjs"` in a .d.ts file to prevent warnings on import statements.

**Comment by riderx** [comment]
i switched to `vue-chartjs`
