### ISSUE TITLE
Cannot read property 'Chart' of undefined

### ISSUE THREAD

**Issue by admin-2020** [J-T-McC/vue3-chartjs#12]
Hey, getting this error when including the umd build:

Cannot read property 'Chart' of undefined

I have included Chart.js and tested it is all loaded and working as expected before including vue3-chartjs. Am i wrong in thinking that i can use this by just including the file 'vue3-chartjs.umd.js' ?

**Comment by J-T-McC** [comment]
Thanks for reporting. This is fixed in [v1.1.3](https://github.com/J-T-McC/vue3-chartjs/releases/tag/v1.1.3)
