### ISSUE TITLE
Sandbox Examples Problem 

### ISSUE THREAD

**Issue by hgalytoby** [J-T-McC/vue3-chartjs#21]
I am learning Vue.

Sorry, my English is not good.

https://codesandbox.io/s/bar-chart-kog87?file=/src/App.vue

I would like to know what is this for?

```js
options: {
    min: 0,
    max: 100,
}
```

Whether I delete or change the value, I don't see a difference.

**Comment by selmanbaskaya** [comment]
If the chart data is not empty, it is probably balancing itself automatically. Under normal conditions, whichever direction (x or y) indexAxis of the chart is the values entered in the options are the limit values.

**Comment by hgalytoby** [comment]
> If the chart data is not empty, it is probably balancing itself automatically. Under normal conditions, whichever direction (x or y) indexAxis of the chart is the values entered in the options are the limit values.

Thank you.
