### ISSUE TITLE
How to change default aspect ratio of charts

### ISSUE THREAD

**Issue by PracticalGeek1** [J-T-McC/vue3-chartjs#4]
@J-T-McC J-T-McC

Hi Tyson, 

Is there a way to change the default aspect ratio of the rendered chart? I understand I can hard code the chart size using .value.resize(width, height), but most time its size should adjust along the container size. However, the rendered chart always keeps an aspect ratio of about 2:1. 
Is there something I missed from your documents?

Also, it seems value.resize(width, height) isn't working either:
```
chartRef.value.resize(498, 373)  // this has no effect
```

Kind regards
Andy Liao

**Comment by J-T-McC** [comment]
Hi Andy.

The chart should render to the dimensions of its parent container, but keep in mind not all charts are the same. For example, you cant have a pie chart that is 200px wide and 10px tall, it would be 10px tall and wide. 

The charts should resize automatically when your browser & container resize as well. This is a feature of chartjs and not something implemented in this wrapper.

[Example pie and line charts resizing](https://ibb.co/PMVnL9N)
